shiny:
  proxy:
    title: City of Boston Analytics Team
    logo-url: https://www.boston.gov/crispus/images/b-light.svg
    landing-page: /
    heartbeat-rate: 10000
    heartbeat-timeout: 6000000
    port: 8080
    authentication: simple
    admin-groups: scientists
    # Simple auth configuration
    users:
    - name: bfd_analyst
      password: test_fires
      groups: scientists
    - name: imagine-boston
      password: boston2030rocks
      groups: scientists
    - name: housing_analyst
      password: increase-seaward-hoard
      groups: housing
    docker:
      cert-path: /home/none
      url: http://localhost:2375
      host: 127.0.0.1
      port-range-start: 20000
  apps:
  - name: bfd_response_times
    display-name: Boston Fire Department Dashboard
    description: Boston Fire Department Dashboard
    docker-cmd: ["R", "-e shiny::runApp('/root/bfd_dashboard')"]
    docker-image: 811289587868.dkr.ecr.us-west-2.amazonaws.com/bfd_response_times
    groups: scientists

  - name: imagine-boston
    display-name: Imagine Boston 2030
    description: Metrics related to the Imagine Boston 2030 Action Plan
    docker-cmd: ["R", "-e shiny::runApp('/root/imagine_boston')"]
    docker-image: 811289587868.dkr.ecr.us-west-2.amazonaws.com/imagine_boston

  - name: eviction-analysis
    display-name: Eviction Analysis
    description: Shows number of evictions per block group in Boston for 2016
    docker-cmd: ["R", "-e shiny::runApp('/root/evictions')"]
    docker-image: bostonanalytics/eviction_analysis
    groups: housing


logging:
  file:
    shinyproxy.log

