shiny:
  proxy:
    title: Open Analytics Shiny Proxy
    logo-url: http://www.openanalytics.eu/sites/www.openanalytics.eu/themes/oa/logo.png
    landing-page: /
    heartbeat-rate: 10000
    heartbeat-timeout: 60000
    port: 8080
    authentication: simple
    admin-groups: scientists
    # Simple auth configuration
    users:
    - name: jack
      password: password
      groups: scientists
    - name: jeff
      password: password
      groups: mathematicians
    - name: bfd_analyst
      password: test_fires
      groups: scientists
    docker:
      cert-path: /home/none
      url: http://localhost:2375
      host: 127.0.0.1
      port-range-start: 20000
  apps:
  - name: 01_hello
    display-name: Hello Application
    description: Application which demonstrates the basics of a Shiny app
    docker-cmd: ["R", "-e shinyproxy::run_01_hello()"]
    docker-image: openanalytics/shinyproxy-demo
    groups: scientists, mathematicians
  - name: 06_tabsets
    docker-cmd: ["R", "-e shinyproxy::run_06_tabsets()"]
    docker-image: openanalytics/shinyproxy-demo
    groups: scientists
  - name: bfd_response_times
    display-name: Boston Fire Department Dashboard
    description: Boston Fire Department Dashboard
    docker-cmd: ["R", "-e shiny::runApp('/root/bfd_dashboard')"]
    docker-image: bostonanalytics/bfd_response_times
    groups: scientists

logging:
  file:
    shinyproxy.log

