shiny:
  proxy:
    title: City of Boston Analytics Team
    logo-url: https://www.boston.gov/crispus/images/b-light.svg
    landing-page: /
    heartbeat-rate: 10000
    heartbeat-timeout: 60000
    port: 8081
    authentication: none
    admin-groups: scientists
    docker:
      cert-path: /home/none
      url: http://localhost:2375
      host: 127.0.0.1
      port-range-start: 20000
  apps:
  - name: imagine-boston
    display-name: Imagine Boston 2030
    description: Metrics related to the Imagine Boston 2030 Action Plan
    docker-cmd: ["R", "-e shiny::runApp('/root/imagine_boston')"]
    docker-image: bostonanalytics/imagine_boston


logging:
  file:
    shinyproxy.log

