shiny:
  proxy:
    title: City of Boston Analytics Team
    logo-url: https://www.boston.gov/crispus/images/b-light.svg
    landing-page: /
    heartbeat-rate: 10000
    heartbeat-timeout: 6000000
    port: 8080
    authentication: simple
    admin-groups: scientists
    # Simple auth configuration
    users:
    - name: shiny_analyst
      password: cover.navy.wrestle
      groups: analyst
    - name: bfd_analyst
      password: test_fires
      groups: scientists
    - name: housing_analyst
      password: increase-seaward-hoard
      groups: housing
    docker:
      cert-path: /home/none
      url: http://localhost:2375
      host: 127.0.0.1
      port-range-start: 20000
  apps:
  - name: bfd_response_times
    display-name: Boston Fire Department Dashboard
    description: Boston Fire Department Dashboard
    docker-cmd: ["R", "-e shiny::runApp('/root/bfd_dashboard')"]
    docker-image: 811289587868.dkr.ecr.us-east-1.amazonaws.com/bfd_response_times
    groups: scientists, analyst

  - name: imagine-boston
    display-name: Imagine Boston 2030
    description: Metrics related to the Imagine Boston 2030 Action Plan
    docker-cmd: ["R", "-e shiny::runApp('/root/imagine_boston')"]
    docker-image: 811289587868.dkr.ecr.us-east-1.amazonaws.com/imagine_boston

  - name: eviction-analysis
    display-name: Eviction Analysis
    description: Shows number of evictions per block group in Boston for 2016
    docker-cmd: ["R", "-e shiny::runApp('/root/evictions')"]
    docker-image: 811289587868.dkr.ecr.us-east-1.amazonaws.com/eviction_analysis
    groups: housing, analyst

  - name: premature-mortality-analysis
    display-name: Premature Mortality Analysis
    description: Analysis
    docker-cmd: ["R", "-e shiny::runApp('/root/prematuremortality')"]
    docker-image: 811289587868.dkr.ecr.us-east-1.amazonaws.com/premature-mortality-analysis
    groups: housing, analyst

    
  - name: p3-bb-monitoring
    display-name: P3 Back Bay monitoring
    description: Monitors data collection in the Back Bay
    docker-cmd: ["R", "-e shiny::runApp('/root/p3_bb_monitoring')"]
    docker-image: 811289587868.dkr.ecr.us-east-1.amazonaws.com/p3-bb-monitoring
    groups: analyst

logging:
  file:
    shinyproxy.log

